### ISSUE TITLE
Under Licence?

### ISSUE THREAD

**Issue by KoalaGeo** [AstunTechnology/ssdidocs#40]
Hi, is this under any sort of licence or is it able to be reused?

**Comment by archaeogeek** [comment]
Hi,

That's a really good question, thanks for asking! I will need to check with the clients that we provide the documentation for. Can I ask what you want to use it for? (our of curiosity really)

Thanks

Jo

**Comment by KoalaGeo** [comment]
I work for the British Geological Survey, we use Geonetwork ourselves and also help partners implement it as we're currently doing for the survey in Kenya. Obviously good documentation is key and if we can reuse your great documentation and avoid duplication of effort all the better!
I'm hoping as your clients government they'll go for OGL or similar... Fingers crossed

**Comment by archaeogeek** [comment]
Hi,

I've asked the question and they are going to discuss it asap so I'll get back to you as soon as I have an answer.

Jo

**Comment by KoalaGeo** [comment]
That's great, thank you. Maybe dropping a gentle reminder of point 12. and 13. (https://www.gov.uk/service-manual/service-standard) to them would help :-)

**Comment by archaeogeek** [comment]
It's a yes to the OGL. No gentle reminders were needed- it's not that they didn't want to do it, just that it hadn't been considered until now. I'll get it added to the actual documentation asap. As a quid pro quo, if you find any areas that you think need expanding or improving, perhaps you'd consider contributing them back in the form of a pull request?

**Comment by archaeogeek** [comment]
Documentation now contains a licencing section, duplicated in the repository itself for good measure.
