### ISSUE TITLE
Admin Docs - Directories

### ISSUE THREAD

**Issue by alexarobu** [AstunTechnology/ssdidocs#42]
Should there be something related to Gemini 2.3 here? 

> Directories are snippets of information that can be pre-completed and inserted into metadata records. They are derived from subtemplates that are part of metadata standards. The available subtemplates are shown as tabs across the top of the Directory subsection- for Gemini 2.2 these are Organizations and contacts and Online resources.

**Comment by archaeogeek** [comment]
Yes, I think you could say something like 

> for Gemini 2.2 and 2.3 these are Organizations and contacts, and Online resources

Assuming that is correct for Gemini 2.3 as well, of course!
