### ISSUE TITLE
Admin Docs - Standards

### ISSUE THREAD

**Issue by alexarobu** [AstunTechnology/ssdidocs#43]
This whole section is out of date in GeoNetwork 3.12.x

**Comment by archaeogeek** [comment]
https://scottish-sdi-metadata-portal.readthedocs.io/en/3.10.x/ssdi_adminguidance.html#standards agree this is now out of date. It's no longer possible to upload a standard via the user interface. I don't want to suggest removing this section entirely as it will mean re-numbering the following sections and figures. 

I would say something like:

> In GeoNetwork 3.12.x it is no longer possible to add new metadata standards via the user interface. For information on the standards currently loaded in the catalog see xxx. To load a new standard, please contact the catalog administrator

filling in the correct location for xxx and removing figure 7.1.1
