### ISSUE TITLE
Admin docs - Users and Groups - Manage Users

### ISSUE THREAD

**Issue by alexarobu** [AstunTechnology/ssdidocs#44]
In GeoNetwork v3.12.x this functionality seems to be broken 

>Figure 8.2.3: The lower section of the user editing interface

The above section looks like this regardless of how many records are owned by the user:

![image](https://user-images.githubusercontent.com/36423106/194874600-17f11e30-0d8f-4866-a7e8-21c6965d8534.png)

**Comment by archaeogeek** [comment]
I'm not sure where the -1 is coming from, I see it locally but it's working fine on another site running Geonetwork 3.12. I don't think the image or text will change, so we can probably just leave it as is and address it as a bug for ScotGov if it continues on their server
