### ISSUE TITLE
Scotland GIS Data for Parcels and Addresses Question

### ISSUE THREAD

**Issue by justinelliotmeyers** [AstunTechnology/ssdidocs#46]
Does your agency have a write up about why GIS data is not free and open for address points or parcel polygons for Scotland?
I am trying to better understand why the majority of Europe has this data as open data (free) and almost all of the UK/ Ireland only sell the data.

I want to better understand the governments perspective and history of the logic. I appreciate your help.
Justin

**Comment by archaeogeek** [comment]
Thanks for your interest. Access to UK address points and land parcels datasets are managed under the Public Sector Geospatial Agreement, set up between the Geospatial Commission and Royal Mail/Ordnance Survey. For more information please see https://www.ordnancesurvey.co.uk/customers/public-sector/public-sector-geospatial-agreement. While we can't recommend a specific person for you to contact for the background and history of this agreement, you could try the Ordnance Survey using their contact form at https://www.ordnancesurvey.co.uk/contact-us.
